---
- name: Update ub servers
  hosts: u2
  become: yes

  tasks:
  - name: Update apt 
    apt:
      update_cache: true

  - name: Install apache2
    package:
      name: apache2
      state: present

  - name: start apache2
    service:
      name: apache2
      state: started

  - name: enabled apache2
    service:
      name: apache2
      enabled: yes
